version: "3.7"

services:

  redis:
    image: redis:7
    container_name: redis_google_disk_app
    command: --port 6379
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    env_file:
      - .docker.env
    container_name: google_disk_app
    command: ['/fastapi_app/app.sh']
    ports:
      - "8000:8000"
    depends_on:
      - redis
