FILE_TYPES_MAPPING = {
    'application/pdf': 'PDF File',
    'application/x-openvpn-profile': 'OpenVPN Profile',
    'application/vnd.android.package-archive': 'APK File',
    'application/vnd.google-apps.audio': 'Audio',
    'application/vnd.google-apps.document': 'Google Docs Document',
    'application/vnd.google-apps.drawing': 'Google Docs Drawing',
    'application/vnd.google-apps.file': 'Google Drive File',
    'application/vnd.google-apps.folder': 'Folder',
    'application/vnd.google-apps.form': 'Google Forms',
    'application/vnd.google-apps.fusiontable': 'Google Fusion Tables',
    'application/vnd.google-apps.map': 'Google My Maps',
    'application/vnd.google-apps.photo': 'Photo',
    'application/vnd.google-apps.presentation': 'Google Slides Presentation',
    'application/vnd.google-apps.script': 'Google Apps Script',
    'application/vnd.google-apps.site': 'Google Sites',
    'application/vnd.google-apps.spreadsheet': 'Google Sheets Spreadsheet',
    'application/vnd.google-apps.unknown': 'Unknown Google Drive File',
    'application/vnd.google-apps.video': 'Video',
    'application/vnd.google-apps.drive-sdk': '3rd Party Shortcut',
    'application/vnd.openxmlformats-officedocument.presentationml.presentation': 'PowerPoint Presentation',
    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet': 'Excel Spreadsheet',
    'application/vnd.openxmlformats-officedocument.wordprocessingml.document': 'Word Document',
    'application/zip': 'Zip Archive',
    'audio/aac': 'AAC Audio',
    'audio/mp3': 'MP3 Audio',
    'audio/ogg': 'OGG Audio',
    'audio/wav': 'WAV Audio',
    'audio/webm': 'WebM Audio',
    'image/bmp': 'BMP Image',
    'image/gif': 'GIF Image',
    'image/jpeg': 'JPEG Image',
    'image/png': 'PNG Image',
    'image/svg+xml': 'SVG Image',
    'image/tiff': 'TIFF Image',
    'image/vnd.microsoft.icon': 'Icon Image',
    'text/csv': 'CSV File',
    'text/html': 'HTML File',
    'text/plain': 'Plain Text File',
    'text/tab-separated-values': 'TSV File',
    'text/x-python-script': 'Python Script',
    'video/3gpp': '3GP Video',
    'video/mp4': 'MP4 Video',
    'video/mpeg': 'MPEG Video',
    'video/ogg': 'OGG Video',
    'video/quicktime': 'QuickTime Video',
    'video/webm': 'WebM Video',
    'video/x-msvideo': 'AVI Video',
}
